---
version: "2.1"
services:
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    network_mode: host
    ports:
      - "8112:8112"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      #- UMASK_SET=022 #optional
      #- DELUGE_LOGLEVEL=error #optional
      - DELUGE_LOGLEVEL=debug
    volumes:
      - /mnt/docker/configs/deluge.cozzo.net/config:/config
      - /mnt/download/deluge/:/downloads
    restart: unless-stopped
    #volumes:
    #  - /mnt/docker/configs/transmission.cozzo.net/config:/config
    #  - /mnt/download:/shareddata
