---
version: '2'
services:
  pihole01:
    image: "pihole/pihole:latest"
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Los_Angeles
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
      #- /mnt/docker/configs/pihole01/etc-pihole/:/etc/pihole/
      #- /mnt/docker/configs/pihole01/etc-dnsmasq.d/:/etc/dnsmasq.d/
      - /mnt/dockeriscsi/configs/pihole01.cozzo.net/etc-pihole/:/etc/pihole/
      - /mnt/dockeriscsi/configs/pihole01.cozzo.net/etc-dnsmasq.d/:/etc/dnsmasq.d/
