---
version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      #- /mnt/docker/blue/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - /mnt/docker/blue/nginx/config:/etc/nginx
      - /mnt/docker/blue/nginx/logs:/var/log/nginx
      - /mnt/docker/blue/nginx/logs:/etc/nginx/logs
      - /mnt/docker/blue/nginx80/www:/var/www:ro
      #- /mnt/docker/blue/nginx/config/fastcgi.conf:/etc/nginx/fastcgi.conf
      #- /mnt/docker/blue/nginx/config/mime.types:/etc/nginx/mime.types
      #- /mnt/docker/blue/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      #- /mnt/docker/blue/nginx/config/proxy.conf:/etc/nginx/proxy.conf
      - /mnt/docker/certs:/etc/letsencrypt:ro
      #- /mnt/docker/blue/certbot/www:/var/www/certbot:ro
      #- /mnt/docker/blue/nginx/www/cozzo.net:/var/www/certbot
    ports:
      #- 80:80
      - 443:443
