---
version: '2.2'
services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    #user: "1001:1001"
    user: "0:0"
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    environment:
      - TZ=America/Los_Angeles
      - PUID=1001
      - PGID=1001
      - SESSION_SECRET=
    restart: unless-stopped
    network_mode: host
    privileged: true
    #networks:
    #  - zwave
    devices:
      - '/dev/ttyACM0:/dev/ttyACM0'
    volumes:
      - /mnt/docker/configs/zwave.cozzo.net/config:/usr/src/app/store
      #- /mnt/docker/configs/zwave.cozzo.net/config:/opt/ozw/config
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for zwave-js websocket server
#networks:
#  zwave:
# volumes:
#   zwavejs2mqtt:
#     name: zwavejs2mqtt
