version: "2"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - /mnt/dockeriscsi/configs/dns01.cozzo.net/workdir/:/opt/adguardhome/work
      - /mnt/dockeriscsi/configs/dns01.cozzo.net/config/:/opt/adguardhome/conf
    restart: unless-stopped
