---
# https://grafana.com/docs/grafana/latest/installation/docker/
version: '2'

services:
  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - 3000:3000
    user: "1001"
    volumes:
      - /mnt/docker/configs/grafana.cozzo.net/usr:/usr/share/grafana
      - /mnt/docker/configs/grafana.cozzo.net/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /mnt/docker/configs/grafana.cozzo.net/grafana/provisioning:/etc/grafana/provisioning
      - /mnt/docker/configs/grafana.cozzo.net/lib:/var/lib/grafana
      - /mnt/docker/configs/grafana.cozzo.net/log:/var/log/grafana
      - /mnt/docker/configs/grafana.cozzo.net/plugins:/var/lib/grafana/plugins


version: "3.7"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
            - ~/prometheus-grafana/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    volumes:
            - ~/prometheus-grafana/grafana/grafana.ini:/etc/grafana/grafana.ini
            - ~/prometheus-grafana/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - 3000:3000
    links:
            - prometheus
